# Generated by Django 4.2.17 on 2025-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='_state',
            field=models.BooleanField(default=True),
        ),
    ]
