# Generated by Django 4.2.17 on 2025-04-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course__state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='_state',
            new_name='statution',
        ),
    ]
