# Generated by Django 4.2.17 on 2025-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_course_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='codeyad'),
        ),
    ]
